version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_NAME: snackforest
      DB_USER: root
      DB_PASSWORD: password
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: snackforest
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: